### ISSUE TITLE
Not working on High Sierra

### ISSUE THREAD

**Issue by jakibaki** [koekeishiya/chwm-sa#1]
I just tried to install chwm-sa on the High Sierra beta 17A291m. 

The installation itself seemed to work flawlessly (everything compiled without any problem) but after moving the CHWMInjector.osax to /System/Library/ScriptingAdditions and rebooting it doesn't seem to get loaded properly.

The inject executable outputs the following:

    process found
    2017-07-13 08:34:47.164 inject[857:9639] warning: failed to get scripting definition from 
    /System/Library/CoreServices/Dock.app; it may not be scriptable.
    event sent

Here is the output of ls -la  /System/Library/ScriptingAdditions:

    total 0
    drwxr-xr-x   9 root  wheel   288 Jul 12 21:43 .
    drwxr-xr-x  98 root  wheel  3136 Jul  6 23:52 ..
    drwxr-xr-x@  3 root  wheel    96 Sep 14  2016 BartenderSystemHelper.osax
    drwxr-xr-x   3 root  wheel    96 Jul 12 21:43 CHWMInjector.osax
    drwxr-xr-x   3 root  wheel    96 Jun 11 02:49 Digital Hub Scripting.osax
    drwxr-xr-x@  3 root  wheel    96 Jul  9 09:55 SIMBL.osax
    drwxr-xr-x   3 root  wheel    96 Jun 11 02:47 StandardAdditions.osax
    drwxr-xr-x   3 root  wheel    96 Jul 10 14:44 TotalFinderSIP.osax
    drwxr-xr-x@  3 root  wheel    96 Jul 12 13:25 TotalSpaces.osax

Sorry that I couldn't provide a better bug report but I can't find anything on how to debug Scripting Additions.

**Comment by dominiklohmann** [comment]
It does work regardless of that error message on High Sierra. Did you run the inject binary after rebooting?

**Comment by jakibaki** [comment]
Yes I did. You're right, for some reason it works now! (I could have sworn that it didn't 5 minutes ago). 

Thank you very much!
