### ISSUE TITLE
Desktop switching not working

### ISSUE THREAD

**Issue by Alan01252** [koekeishiya/chwm-sa#10]
Hi all,

Trying to switch desktop but got stuck trying to debug. Dock is running on listening on port 5050 but trying to switch desktops nothing happens, the Dock process doesn't crash, and in the chunkwm manager log I see

`"chunkwm: processing event of type 'ChunkWM _PluginCommand'`

but nothing else if i run

`echo space 2 | nc 127.0.0.1 5050`

Nothing happens either, are there any further logs I can investigate to see what is/isn't happening?

Thanks

Alan

p.s I installed the sa scripts using both manual methods, and the chunkwm install methods

**Comment by koekeishiya** [comment]
> echo space 2 | nc 127.0.0.1 5050

If you try to use desktop switching outside of chunkc to signal chunkwm, you need to find the space-id. These are not the same as the one shown in mission-control. chunkwm translates  mission-control indexes to this proper space id before sending it along to the Dock.

e.g : `chunkc tiling::desktop --focus 2` is not the same as `echo space 2 | nc 127.0.0.1 5050`

Also, you must be running High Sierra for desktop switching to work.

**Comment by Alan01252** [comment]
Thank you!!

Upgrading now to High Sierra feel that's probably what's causing this.
