### ISSUE TITLE
noobie howto  

### ISSUE THREAD

**Issue by imagnma** [koekeishiya/chwm-sa#12]
installed -sa however, I'm lost how can i use all the following 
The Dock will now spawn a local unix domain socket and starts listening on port 5050.

To set window alpha, send: window_alpha <cgwindowid> <alpha>

To fade into window alpha, send: window_alpha_fade <cgwindowid> <alpha> <duration>

To set window level, send: window_level <cgwindowid> <kCGWindowLevelKey>

To set window sticky (show on all spaces), send: window_sticky <cgwindowid> <1 | 0>

To set window position, send: window_move <cgwindowid> <x> <y>

To set window shadow, send: window_shadow <cgwindowid> <1 | 0>

To switch to a different space, bypassing animation, send: space <cgsspaceid>

To create a new space on the active display, send: space_create <focused_cgsspaceid_of_a_display>

To destroy the active space, send: space_destroy <focused_cgsspaceid_of_a_display>

where and how  :(

**Comment by koekeishiya** [comment]
I'm assuming you are using chunkwm. These are the config options that you can enable in your *.chunkwmrc* file, that uses chwm-sa:
```
chunkc set window_float_topmost          1
chunkc set window_fade_inactive          1
chunkc set window_fade_alpha             0.85
chunkc set window_fade_duration          0.25
chunkc set window_use_cgs_move           1
```

With chwm-sa installed, the following commands allows you to interact with spaces:
```
chunkc tiling::desktop --focus 1
chunkc tiling::desktop --create
chunkc tiling::desktop --annihilate
```
These will focus desktop1, createa new desktop, and destroy active desktop respectively.

**Comment by imagnma** [comment]
Oh okay , everything on cfc < terminal shortcut for .chunkwmrc
For killing shadows, do I have to be specific on which application window or I can’t do it all. 

and what more to leverage -sa 

Thanks ❤️❤️

**Comment by koekeishiya** [comment]
To disable shadows, you have to specify a window.

I think you can install the chunkwm purify plugin with brew, to disable shadows for ALL windows.
See: https://github.com/crisidev/homebrew-chunkwm#brew-options

**Comment by imagnma** [comment]
hmmm I typed in terminal 
`brew install --with-purify chunkwm`
crisidev/chunkwm/chunkwm 0.4.5 is already installed and up-to-date
To reinstall 0.4.5, run `brew reinstall chunkwm`

I went ahead and checked /usr/local/opt/chunkwm/share/chunkwm/plugins for the plugin and isnt installled 
:( what did I missed, wrong argument?

**Comment by koekeishiya** [comment]
You need to uninstall first, or maybe just: `brew reinstall --with-purify chunkwm

**Comment by imagnma** [comment]
tried both 
now when I uninstalled  I written 
`~ brew install --with-purify --HEAD chunkwm`                                                                                                                                           
`
==> Installing chunkwm from crisidev/chunkwm
==> Cloning https://github.com/koekeishiya/chunkwm.git
Updating /Users/mo/Library/Caches/Homebrew/chunkwm--git
From https://github.com/koekeishiya/chunkwm
   dfea3c1..6433ad0  master     -> origin/master
==> Checking out branch master
Already on 'master'
==> make install
==> make --directory src/chunkc
==> make install --directory src/plugins/tiling
==> make install --directory src/plugins/ffm
==> make install --directory src/plugins/border
==> make install --directory src/plugins/purify
==> Caveats
Copy the example configuration into your home directory:
  cp /usr/local/opt/chunkwm/share/chunkwm/examples/chunkwmrc ~/.chunkwmrc

Opening chunkwm will prompt for Accessibility API permissions. After access
has been granted, the application must be restarted.
  brew services restart chunkwm

This has to be done after every update to chunkwm, unless you codesign the
binary with self-signed certificate before restarting
Create code signing certificate named "chunkwm-cert" using Keychain Access.app
  codesign -fs "chunkwm-cert" /usr/local/opt/chunkwm/bin/chunkwm

NOTE: options "--with-logging" and "--with-tmp-logging" are deprecated since now
chunkwm supports logging through configuration:
  chunkc core::log_file <stdout | stderr | /path/to/file>

NOTE: plugins folder has been moved to /usr/local/opt/chunkwm/share/chunkwm/plugins

To have launchd start crisidev/chunkwm/chunkwm now and restart at login:
  brew services start crisidev/chunkwm/chunkwm
Or, if you don't want/need a background service you can just run:
  chunkwm
==> Summary
🍺  /usr/local/Cellar/chunkwm/HEAD-6433ad0: 14 files, 538.1KB, built in 14 seconds
~ Rcfc                                                                                                                                                                                         21:05
==> Successfully started `chunkwm` (label: homebrew.mxcl.chunkwm)
` 
everything seems okay here. right? 

this also my confq 
`
#!/bin/bash
chunkc core::plugin_dir ~/.chunkwm_plugins
chunkc core::plugin_dir /usr/local/opt/chunkwm/share/chunkwm/plugins

chunkc set global_desktop_mode           bsp
chunkc set 2_desktop_mode                bsp
chunkc set 5_desktop_mode                float

chunkc set global_desktop_offset_top     70
chunkc set global_desktop_offset_bottom  70
chunkc set global_desktop_offset_left    70
chunkc set global_desktop_offset_right   70
chunkc set global_desktop_offset_gap     40

chunkc set desktop_padding_step_size     10.0
chunkc set desktop_gap_step_size         5.0

chunkc set bsp_spawn_left                1
chunkc set bsp_optimal_ratio             1.618
chunkc set bsp_split_mode                optimal
chunkc set bsp_split_ratio               0.5

chunkc set monitor_focus_cycle           1
chunkc set window_focus_cycle            monitor

chunkc set mouse_follows_focus           0
chunkc set window_float_next             0
chunkc set window_float_center           1
chunkc set window_region_locked          1

chunkc set mouse_modifier                fn

chunkc set preselect_border_color        0xffd75f5f
chunkc set preselect_border_width        5
chunkc set preselect_border_radius       5
chunkc set focused_border_color          0xff915b5f
chunkc set focused_border_width          8
chunkc set focused_border_radius         3
chunkc set focused_border_skip_floating  1
chunkc set window_shadow                 0

chunkc core::load border.so
chunkc core::load tiling.so
chunkc core::load ffm.so
chunkc core::load purify.so

chunkc tiling::rule --owner "Python" --state tile
chunkc tiling::rule --owner Emacs --except "^$" --state tile
chunkc tiling::rule --owner \"mpv\" --subrole AXStandardWindow --state tile
chunkc tiling::rule --owner \"System Preferences\" --subrole AXStandardWindow --state tile
chunkc tiling::rule --owner \"iTerm2\" --subrole AXStandardWindow --state tile
chunkwm --load-sa
`

does everything look right to you ? am I missing something 

thanks so much

**Comment by koekeishiya** [comment]
That seems fine yes

**Comment by imagnma** [comment]
@koekeishiya I doubled check the plugins file and found the `purify.so` plugin
do you think ;
- it might be a problem with chunkwm -a installl 
- or the fact that my operating system is mojave beta 5 
- or reboot needed 

thanks

**Comment by imagnma** [comment]
when installing chunk -sa I did the following 

`
Once recovery mode has booted up, click the utilities menu in the menubar and open a Terminal.


                    # to disable SIP:
                    csrutil disable

                    # to enable SIP:
                    csrutil enable
                
After you have disabled SIP, you can use the following commands to install / uninstall the scripting addition.


                    # to install scripting-addition
                    sudo chunkwm --install-sa

                    # to remove scripting-addition
                    sudo chunkwm --uninstall-sa
                

`

**Comment by osamine** [comment]
Have you tried 
‘’’
pkill Dock 
‘’’

Followed by restarting the application?

**Comment by imagnma** [comment]
@osamine you mean brew services restart chunkwm ?

**Comment by imagnma** [comment]
i did `pkill Dock brew services restart chunkwm`
and `pkill Dock` 

still the damn shadows lol @osamine
