### ISSUE TITLE
Shadow disable with purify plugin

### ISSUE THREAD

**Issue by imagnma** [koekeishiya/chwm-sa#13]
Hello, 

Finally, disabling window shadows worked, however, when I rebooted and reenabled system integrity protection. things went back to normal. 

system : Mac Mojave 10.14

**Comment by osamine** [comment]
What steps did you take?

Did you run:

chunkwm —load-sa

**Comment by koekeishiya** [comment]
I think you need to have SIP disabled in Mojave. It appears that Apple changed something.
On High Sierra, SIP can be reenabled.

**Comment by imagnma** [comment]
Hmm @koekeishiya do you think  is safe ??? security wise ? 

Thanks

**Comment by koekeishiya** [comment]
I'm no security guy, so not gonna pretend like I know all the implications of this, and so I don't want to give advice on whether disabling SIP is considered safe or not.

With the way I use my mac, I don't see the need for SIP, and so I think these benefits that I am able to gain is worth it for me.

I would encourage you to do your own research regarding this and make your decision then.
