### ISSUE TITLE
macOS Mojave broken

### ISSUE THREAD

**Issue by alextes** [koekeishiya/chwm-sa#15]
I should've known 😭 . No more instant desktop switching for me.

I disabled csrutil, restarted, ran the scripting addition install, reenabled csr, restarted, no desktop switching. Got the below when manually trying to make chunkwm load the scripting addition.
```
❯ chunkwm --load-sa
2018-10-23 12:22:37.310 chunkwm[1187:10456] warning: failed to get scripting definition from /System/Library/CoreServices/Dock.app; it may not be scriptable.
chunkwm: successfully loaded sa!
```

Just putting this here so more careful souls, smart enough to check before upgrading are warned and so that there's something to track progress on supporting Mojave.

Let me know if there's anything I can do to help, and thanks for a great tiling desktop manager!

**Comment by dominiklohmann** [comment]
Straight from the README:

> If you are running High Sierra or an earlier version, reboot into recovery mode and enable SIP.

On Mojave SIP needs to be disabled for injecting the scripting addition into `Dock.app`. This means that you cannot re-enable SIP on Mojave.

**Comment by alextes** [comment]
I would've guessed this was because the README is out of date with the recent update, but it appears Mojave has been out for a while!

Regardless, let me try what you propose and if it works, I can perhaps PR a doc update that is explicit about the fact that on Mojave and higher SIP is to remain disabled.

**Comment by koekeishiya** [comment]
The line copied from the README by @dominiklohmann was my way of saying that Mojave (and all future macOS versions) require SIP to remain disabled. 

All functionality provided by chwm-sa still work on Mojave, I use it daily (and have ever since the first Mojave public Beta).

**Comment by alextes** [comment]
I understand. The above was my way of saying that it was hard for me to tell whether a contributor wrote the README in a world where Mojave didn't exist or tried to explain implicitly that Mojave and any future versions of macOS would need SIP to remain disabled.

Being explicit would solve that, but as it turns out Mojave has been out for a month, and there seem to be no other issues reported by people similarly misreading the README.

Neither of you seems keen on updating the copy 😅. In that case, my usual proposal is to close the issue, let people upvote it if they run into the same problem, and if a handful of upvotes show up, I'd be happy to PR a README update to make the instruction explicit.

Thanks again 🙏!
