### ISSUE TITLE
How do I disable shadows for all spaces?

### ISSUE THREAD

**Issue by slifin** [koekeishiya/chwm-sa#17]
I'm using totalspaces to manage my spaces and have a set amount of them

I've managed to disable shadows on one window using 

```
chunkc set window_shadow 0
```
in ```~/.chunkwm``` but from my understanding that first parameter is the window id (not on or off), but I don't know what the ids of any of my windows are

**Comment by dominiklohmann** [comment]
`brew install chunkwm --with-purify` and then `chunkc core::load purify.so`.

See https://github.com/koekeishiya/chunkwm/tree/master/src/plugins/purify.

**Comment by slifin** [comment]
Yep I have purify loaded + reinstalled chunkwm with the plugin

I have discovered if I go to a space and then run brew services restart chunkwm on that space the shadows disappear, then I can repeat that for every space, but if I do pkill Dock all shadows return

**Comment by slifin** [comment]
Looks like this works as a workaround, although it does extra stuff I didn't really want:
https://github.com/w0lfschild/mySIMBL with winbuddy

**Comment by koekeishiya** [comment]
>  I have discovered if I go to a space and then run brew services restart chunkwm inside a terminal, inside that space the shadows disappear, then I can repeat that for every space,

Coincidentally, I think I've just randomly thought of a way to bypass this restriction.

> but if I do pkill Dock all shadows return

I have not been able to reproduce this on my end, but why would you need to force kill the Dock though?

**Comment by koekeishiya** [comment]
I found an API to remove the window shadow that does not reset when the Dock is killed, however I am unable to restore the windows shadow afterwards.

**Comment by koekeishiya** [comment]
The latest chunkwm-sa has been updated with a command that disables shadows permanently. I have made an update to the purify plugin that uses this new command. Even if the Dock restarts, shadows will be disabled. NOTE: You can not undo the shadow removal by using `window_shadow <..> 1`, and have to restart the application / close-reopen window entirely.

I have also changed how the purify plugin works when detecting already opened windows, and now ALL windows that are visible across all spaces across all monitors will have their shadows removed instantaneously upon load.

Update chunkwm from master, then update chunkwm-sa using the built-in commands as usual, and enjoy a shadowless experience.

**Comment by slifin** [comment]
I've run 

```
brew remove chunkwm
brew install chunkwm --with-purify --HEAD
```
Added to ```~/.chunkwmrc```
```
chunkc core::load purify.so
chunkwm --load-sa
```
I can see a string of ```window_shadow_irreversible``` inside purify.so so I assume I have what I need there

But I don't get shadow removal, is there something I'm missing?

**Comment by dominiklohmann** [comment]
Are you by chance running the current 10.14.4 beta version of macOS? The scripting addition is broken for that version of Dock.app.

**Comment by slifin** [comment]
I've not opted into any beta for macOS, and other chwm-sa commands like ```
chunkc tiling::desktop --focus 1``` work ok

**Comment by koekeishiya** [comment]
Works just fine for me. Try the following:

´``
# stop chunkwm..

sudo chunkwm --uninstall-sa
pkill Dock
sudo chunkwm --install-sa

# start chunkwm..
```

I'm running this on Mojave 10.14.3 and works fine.

**Comment by slifin** [comment]
yep that worked, I did have to do it a couple of times which was weird but no shadows 👍
