### ISSUE TITLE
Error on running build.sh

### ISSUE THREAD

**Issue by capaldo** [koekeishiya/chwm-sa#18]
Running build.sh produces the following error:

```bash
payload.mm:640:5: warning:
      'GetProcessForPID' is deprecated:
      first deprecated in macOS 10.9
      [-Wdeprecated-declarations]
    GetProcessForPID(window_pid, &...
    ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/ApplicationServices.framework/Frameworks/HIServices.framework/Headers/Processes.h:930:1: note:
      'GetProcessForPID' has been
      explicitly marked deprecated here
GetProcessForPID(
^
1 warning generated.
```

**Comment by koekeishiya** [comment]
Not an error, just a warning for use of a deprecated function. The function is still working as expected, and Apple have yet to provide documentation for an alternative solution. I'll update the build script to ignore this warning.

**Comment by dominiklohmann** [comment]
May I suggest wrapping the code with pragmas to ignore the deprecation warning instead of using `-Wno-deprecated-declarations` for everything? This way newly added code will still trigger the warning.

```cpp
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

// code

#pragma clang diagnostic pop
```

**Comment by koekeishiya** [comment]
Yep that's what I ended up doing. Have done similar in other projects that uses these APIs.

**Comment by koekeishiya** [comment]
Actually found a single function to get the psn directly from the connection. No need to use this function. So much good stuff to be found inside the Dock binary.
