### ISSUE TITLE
focus, create, and annihilate broken on latest release of macOS 10.14.4

### ISSUE THREAD

**Issue by RosalesJ** [koekeishiya/chwm-sa#19]
## Issue
Directly after upgrading to the latest ```macOS 10.14.4``` fast window switching stopped working. The following commands when run in the command line do nothing without any errors.
```
chunkc tiling::desktop --focus 3
chunkc tiling::desktop --create
chunkc tiling::desktop --annihilate
```
When starting sa the following occurs
```
➜  ~ chunkwm --load-sa
2019-04-04 19:33:43.642 chunkwm[26688:132060] warning: failed to get scripting definition from /System/Library/CoreServices/Dock.app; it may not be scriptable.
chunkwm: successfully loaded sa!
```
## Reproduction
As stated above I'm running ```macOS 10.14.4``` and 
```
➜  ~ chunkwm --version
chunkwm 0.4.8 ()
```

**Comment by adinapoli** [comment]
Sob, I do confirm the same behaviour -- @koekeishiya , any pro trick to restore the old behaviour?

I am also running macOS 10.14.4 and:

```
~ > chunkwm --version                                                                                                                                                                                                                        
chunkwm 0.4.8 (2f84)
```

**Comment by adinapoli** [comment]
@RosalesJ oh, our good man @koekeishiya already posted in [another place](https://github.com/koekeishiya/chunkwm/issues/571#issuecomment-477360495) the steps to restore the old behaviour:

```
brew reinstall --HEAD chunkwm
sudo chunkwm --uninstall-sa
pkill Dock
sudo chunkwm --install-sa
brew services start chunkwm
```

I do confirm this does the trick on my machine 🎉 

Amazing project, I love it 😉

**Comment by RosalesJ** [comment]
Wonderful!

It was a different permutation of these commands, along with restarting, which resolved this for me, but my issue is now fixed.

Thanks @adinapoli and @koekeishiya !
