### ISSUE TITLE
Unable to run chwm-sa on sierra

### ISSUE THREAD

**Issue by crisidev** [koekeishiya/chwm-sa#2]
I just tried to install chwm-sa on Sierra

The installation itself seemed to work flawlessly (everything compiled without any problem) but after moving the CHWMInjector.osax to /System/Library/ScriptingAdditions and rebooting it doesn't seem to get loaded properly.

The inject executable outputs the following:

```
process found 2017-07-15 08:34:47.164 inject[857:9639] warning: failed to get scripting definition from /System/Library/CoreServices/Dock.app; it may not be scriptable. event sent 
```

The osax is installed in  /System/Library/ScriptingAdditions and I followed the guide:
* reboot in recovery and disable system protection
* reboot and copy the osax inside /System/Library/ScriptingAdditions
* reboot in recovery and enable system protection
* reboot

I don't know how to debug this issue. Any idea?

**Comment by koekeishiya** [comment]
that warning is normal. what's the output of `lsof -i :5050` ??

if the Dock crashes upon inject, you need to (sudo) codesign the binaries inside the scripting addition. see the last 2 lines of the *build.sh script in the root folder.

**Comment by crisidev** [comment]
Lsof does not show anything and the dock is not crashing.. I'll try to sudo codesign what's needed and reinstall the script addition.

**Comment by crisidev** [comment]
sudo codesigning the bundle worked. Thanks!!
