### ISSUE TITLE
How do i run inject script at startup?

### ISSUE THREAD

**Issue by scottgrayson** [koekeishiya/chwm-sa#3]
This is working well for me after i run `./inject` but it does not get run at startup. is there a plist I can add? or do i need to reference the script somewhere?

**Comment by koekeishiya** [comment]
You can indeed use *launchd* for this. The following *.plist* should work

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>my.login.item</string>
    <key>ProgramArguments</key>
    <array>
        <string>/path/to/binary</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
</dict>
</plist>
```

Some information regarding launchd if you want to understand more about it: http://www.launchd.info/

**Comment by scottgrayson** [comment]
Thanks. As a test, i tried running it from the .chwmrc file. This works also
