### ISSUE TITLE
Best way to issue chwm-sa commands?

### ISSUE THREAD

**Issue by xaviervalarino** [koekeishiya/chwm-sa#6]
I've been using the chwm-sa commands using `netcat`, _e.g._,
```
echo window shadow <cgwindowid> 0 | nc 127.0.0.1 5050
```
and was wondering if there is a more canonical way to issue chwm-sa commands.

**Comment by koekeishiya** [comment]
Uh, personally I use the [*purify*](https://github.com/koekeishiya/chunkwm/tree/master/src/plugins/purify) plugin for *chunkwm*. It is not officially released though.

The plugin basically removes the shadows of all the applications / windows that are opened after the plugin has been loaded. It also tries to remove the shadows of windows that are visible when the plugin is loaded, but that only affects the active desktop if I remember correctly.

I'm sure you could modify that plugin to your liking, it consists of ~100loc and should be fairly easy to understand.

**Comment by koekeishiya** [comment]
The intended use behind *chwm-sa* is to have some other application issue the commands on some event, rather than directly sending a command to *chwm-sa*.

Although you could create some bind in *skhd* that could query the focused windows *cgwindowid* and then issue any *chwm-sa* command with that windowid.

**Comment by xaviervalarino** [comment]
I've been messing around with purify and really like having the shadowless tiled windows but wanted to do something similar to santip in #4 where floating windows had shadows applied. 

I might take a stab at modifying  purify for that behavior. Also might bind skhd to make`window_sticky` and change `window_level`.

I know you don't consider purify as an official plugin, but, for what it's worth, I think purify has merit in some form or another as a plugin.

Thanks for the response and awesome wm!

**Comment by theonlygusti** [comment]
@xaviervalarino  how do you find out cgwindowid and cgspaceid
