### ISSUE TITLE
Cannot launch on High Sierra after reinstalls/re-codesigning

### ISSUE THREAD

**Issue by tinder-jonathanwilner** [koekeishiya/chwm-sa#7]
Similiar to #2 - I've rebuilt and reinstalled multiple times on High Sierra. 

I get the "it may not be scriptable" error, but lsof -i returns fine. 

> ❯ bin/inject 
process found
2018-05-08 11:12:30.206 inject[1265:18630] warning: failed to get scripting definition from /System/Library/CoreServices/Dock.app; it may not be scriptable.
event sent

> ❯  lsof -i :5050
COMMAND PID           USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
Dock    427 jonathanwilner   29u  IPv4 0x205bb5af055bdc0d      0t0  TCP localhost:mmcc (LISTEN)

**Comment by koekeishiya** [comment]
The warning you get is normal, and is not an indication that an error has occurred.
As long as `lsof -i :5050` shows that the Dock is listening, all is well.

**Comment by koekeishiya** [comment]
This is now bundled with chunkwm, see scripting addition entry at https://koekeishiya.github.io/chunkwm/docs.html
